import { useState } from 'react';
import ReportModal from './ReportModal';

function AnalysisDetailModal({ analysis, onClose }) {
  const [showReportModal, setShowReportModal] = useState(false);
  const [copied, setCopied] = useState(false);

  const isBullying = analysis.prediction === 'Cyberbullying Detected';

  const getSeverityLevel = (confidence) => {
    if (confidence >= 0.8) return { label: 'High', color: 'text-red-600 bg-red-100' };
    if (confidence >= 0.6) return { label: 'Medium', color: 'text-orange-600 bg-orange-100' };
    return { label: 'Low', color: 'text-yellow-600 bg-yellow-100' };
  };

  const severity = isBullying ? getSeverityLevel(analysis.confidence) : null;

  const categoryLabels = {
    toxic: { label: 'Toxic', icon: '🔴' },
    severe_toxic: { label: 'Severe Toxic', icon: '⛔' },
    obscene: { label: 'Obscene', icon: '🚫' },
    threat: { label: 'Threat', icon: '⚠️' },
    insult: { label: 'Insult', icon: '💢' },
    identity_hate: { label: 'Identity Hate', icon: '🚨' }
  };

  const generateReportText = () => {
    const timestamp = new Date(analysis.timestamp).toLocaleString();
    return `
CYBERBULLYING ANALYSIS REPORT
Analysis ID: ${analysis._id}
Timestamp: ${timestamp}

MESSAGE ANALYZED:
"${analysis.text}"

ANALYSIS RESULTS:
- Detection: ${analysis.prediction}
- Confidence: ${(analysis.confidence * 100).toFixed(1)}%
- Language: ${analysis.language || 'English'}
- Severity: ${severity ? severity.label : 'N/A'}

TOXICITY CATEGORIES DETECTED:
${analysis.categories ? Object.entries(analysis.categories)
  .filter(([_, value]) => value === 1)
  .map(([key, _]) => `- ${key.replace('_', ' ').toUpperCase()}`)
  .join('\n') : 'N/A'}

${analysis.toxicKeywords && analysis.toxicKeywords.length > 0 ? 
`TOXIC KEYWORDS IDENTIFIED:
${analysis.toxicKeywords.map(k => `- ${k}`).join('\n')}` : ''}

---
Generated by Cyberbullying Detection Platform
    `.trim();
  };

  const handleCopyReport = () => {
    const reportText = generateReportText();
    navigator.clipboard.writeText(reportText);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <>
      <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50 p-4">
        <div className="bg-white rounded-lg shadow-2xl max-w-3xl w-full max-h-[90vh] overflow-y-auto">
          <div className="p-6">
            {/* Header */}
            <div className="flex justify-between items-start mb-6">
              <div className="flex-1">
                <h2 className="text-2xl font-bold text-gray-800 mb-2">Analysis Report</h2>
                <p className="text-sm text-gray-600">
                  {new Date(analysis.timestamp).toLocaleString()}
                </p>
              </div>
              <button
                onClick={onClose}
                className="text-gray-500 hover:text-gray-700 text-3xl leading-none"
              >
                ×
              </button>
            </div>

            {/* Detection Result */}
            <div className={`p-4 rounded-lg border-2 mb-6 ${
              isBullying 
                ? 'bg-red-50 border-red-300' 
                : 'bg-green-50 border-green-300'
            }`}>
              <div className="flex items-center justify-between mb-3">
                <h3 className={`text-xl font-bold ${
                  isBullying ? 'text-red-700' : 'text-green-700'
                }`}>
                  {isBullying ? '⚠️ Cyberbullying Detected' : '✅ Safe Message'}
                </h3>
                <div className="flex items-center gap-2">
                  {analysis.language && (
                    <span className="text-xs font-semibold px-3 py-1 rounded bg-blue-100 text-blue-800">
                      {analysis.language === 'hindi' ? '🇮🇳 Hindi' : 
                       analysis.language === 'telugu' ? '🇮🇳 Telugu' : 
                       '🇬🇧 English'}
                    </span>
                  )}
                  {severity && (
                    <span className={`px-3 py-1 rounded-full text-sm font-semibold ${severity.color}`}>
                      {severity.label} Severity
                    </span>
                  )}
                </div>
              </div>
              
              <div className="mb-3">
                <p className="text-sm text-gray-700 font-semibold mb-1">Confidence Score:</p>
                <div className="flex items-center gap-3">
                  <div className="flex-1 bg-gray-200 rounded-full h-3">
                    <div
                      className={`h-3 rounded-full ${isBullying ? 'bg-red-500' : 'bg-green-500'}`}
                      style={{ width: `${analysis.confidence * 100}%` }}
                    />
                  </div>
                  <span className="font-bold text-lg">
                    {(analysis.confidence * 100).toFixed(0)}%
                  </span>
                </div>
              </div>
            </div>

            {/* Message Content */}
            <div className="mb-6">
              <h4 className="font-semibold text-gray-800 mb-2">Message Content:</h4>
              <div className="bg-gray-50 p-4 rounded-lg border border-gray-200">
                <p className="text-gray-700 whitespace-pre-wrap">{analysis.text}</p>
              </div>
            </div>

            {/* Toxicity Categories */}
            {isBullying && analysis.categories && (
              <div className="mb-6">
                <h4 className="font-semibold text-gray-800 mb-3">Toxicity Categories:</h4>
                <div className="grid grid-cols-2 gap-3">
                  {Object.entries(analysis.categories).map(([key, value]) => {
                    const config = categoryLabels[key];
                    const isDetected = value === 1;
                    
                    return (
                      <div
                        key={key}
                        className={`p-3 rounded-lg border-2 ${
                          isDetected
                            ? 'bg-red-50 border-red-300'
                            : 'bg-gray-50 border-gray-200 opacity-50'
                        }`}
                      >
                        <div className="flex items-center gap-2">
                          <span className="text-xl">{config.icon}</span>
                          <div>
                            <p className={`text-sm font-bold ${
                              isDetected ? 'text-gray-800' : 'text-gray-500'
                            }`}>
                              {config.label}
                            </p>
                            <p className="text-xs text-gray-600">
                              {isDetected ? '✓ Detected' : '✗ Not detected'}
                            </p>
                          </div>
                        </div>
                      </div>
                    );
                  })}
                </div>
              </div>
            )}

            {/* Toxic Keywords */}
            {isBullying && analysis.toxicKeywords && analysis.toxicKeywords.length > 0 && (
              <div className="mb-6">
                <h4 className="font-semibold text-gray-800 mb-2">Toxic Keywords Detected:</h4>
                <div className="flex flex-wrap gap-2">
                  {analysis.toxicKeywords.map((keyword, idx) => (
                    <span
                      key={idx}
                      className="px-3 py-1 bg-red-200 text-red-900 rounded-full text-sm font-semibold"
                    >
                      {keyword}
                    </span>
                  ))}
                </div>
              </div>
            )}

            {/* Action Buttons */}
            <div className="flex gap-3">
              <button
                onClick={handleCopyReport}
                className="flex-1 bg-indigo-600 text-white py-3 px-4 rounded-lg font-semibold hover:bg-indigo-700 transition-colors"
              >
                {copied ? '✓ Copied!' : '📋 Copy Report'}
              </button>
              
              {isBullying && (
                <button
                  onClick={() => setShowReportModal(true)}
                  className="flex-1 bg-red-600 text-white py-3 px-4 rounded-lg font-semibold hover:bg-red-700 transition-colors"
                >
                  📢 Report to Authorities
                </button>
              )}
            </div>
          </div>
        </div>
      </div>

      {showReportModal && (
        <ReportModal
          result={{
            prediction: analysis.prediction,
            confidence: analysis.confidence,
            categories: analysis.categories,
            toxicKeywords: analysis.toxicKeywords,
            language: analysis.language
          }}
          originalText={analysis.text}
          onClose={() => setShowReportModal(false)}
        />
      )}
    </>
  );
}

export default AnalysisDetailModal;
