import { useState } from 'react';

function ReportModal({ result, originalText, onClose }) {
  const [selectedPortal, setSelectedPortal] = useState('');
  const [copied, setCopied] = useState(false);

  const complaintPortals = [
    {
      id: 'cybercrime',
      name: 'National Cyber Crime Reporting Portal (India)',
      url: 'https://cybercrime.gov.in/',
      description: 'Official portal for reporting cybercrimes in India',
      icon: '🇮🇳'
    },
    {
      id: 'ncmec',
      name: 'National Center for Missing & Exploited Children',
      url: 'https://www.cybertipline.org/',
      description: 'Report online exploitation of children',
      icon: '🛡️'
    },
    {
      id: 'ic3',
      name: 'FBI IC3 (Internet Crime Complaint Center)',
      url: 'https://www.ic3.gov/Home/FileComplaint',
      description: 'Report internet crimes to FBI',
      icon: '🇺🇸'
    },
    {
      id: 'stopbullying',
      name: 'StopBullying.gov',
      url: 'https://www.stopbullying.gov/cyberbullying/how-to-report',
      description: 'Resources and reporting guidance',
      icon: '🚫'
    },
    {
      id: 'local',
      name: 'Local Police Department',
      url: '#',
      description: 'Contact your local law enforcement',
      icon: '👮'
    }
  ];

  const generateReportData = () => {
    const timestamp = new Date().toLocaleString();
    return `
CYBERBULLYING ANALYSIS REPORT
Generated: ${timestamp}

MESSAGE ANALYZED:
"${originalText}"

ANALYSIS RESULTS:
- Detection: ${result.prediction}
- Confidence: ${(result.confidence * 100).toFixed(1)}%
- Language: ${result.language || 'English'}

TOXICITY CATEGORIES DETECTED:
${result.categories ? Object.entries(result.categories)
  .filter(([_, value]) => value === 1)
  .map(([key, _]) => `- ${key.replace('_', ' ').toUpperCase()}`)
  .join('\n') : 'N/A'}

${result.toxicKeywords && result.toxicKeywords.length > 0 ? 
`TOXIC KEYWORDS IDENTIFIED:
${result.toxicKeywords.map(k => `- ${k}`).join('\n')}` : ''}

SEVERITY LEVEL: ${result.confidence >= 0.8 ? 'HIGH' : result.confidence >= 0.6 ? 'MEDIUM' : 'LOW'}

---
This report was generated by Cyberbullying Detection Platform
AI-powered analysis for harmful content detection
    `.trim();
  };

  const handleCopyReport = () => {
    const reportData = generateReportData();
    navigator.clipboard.writeText(reportData);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleReportToPortal = (portal) => {
    if (portal.id === 'local') {
      alert('Please contact your local police department directly with the copied report data.');
      return;
    }
    
    // Copy report data and open portal
    handleCopyReport();
    window.open(portal.url, '_blank');
  };

  return (
    <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50 p-4">
      <div className="bg-white rounded-lg shadow-2xl max-w-3xl w-full max-h-[90vh] overflow-y-auto">
        <div className="p-6">
          <div className="flex justify-between items-center mb-6">
            <h2 className="text-2xl font-bold text-gray-800">📢 Report Cyberbullying</h2>
            <button
              onClick={onClose}
              className="text-gray-500 hover:text-gray-700 text-2xl"
            >
              ×
            </button>
          </div>

          <div className="mb-6 p-4 bg-yellow-50 border border-yellow-200 rounded-lg">
            <p className="text-sm text-yellow-800">
              <strong>Important:</strong> If you're experiencing immediate danger, please call emergency services (911 in US, 100 in India) immediately.
            </p>
          </div>

          <div className="mb-6">
            <h3 className="text-lg font-semibold text-gray-800 mb-3">Analysis Summary</h3>
            <div className="bg-red-50 border border-red-200 rounded-lg p-4">
              <div className="grid grid-cols-2 gap-3 text-sm">
                <div>
                  <span className="text-gray-600">Detection:</span>
                  <span className="ml-2 font-semibold text-red-700">{result.prediction}</span>
                </div>
                <div>
                  <span className="text-gray-600">Confidence:</span>
                  <span className="ml-2 font-semibold text-red-700">{(result.confidence * 100).toFixed(1)}%</span>
                </div>
                <div>
                  <span className="text-gray-600">Language:</span>
                  <span className="ml-2 font-semibold">{result.language || 'English'}</span>
                </div>
                <div>
                  <span className="text-gray-600">Toxic Keywords:</span>
                  <span className="ml-2 font-semibold">{result.toxicKeywords?.length || 0}</span>
                </div>
              </div>
            </div>
          </div>

          <div className="mb-6">
            <button
              onClick={handleCopyReport}
              className="w-full bg-indigo-600 text-white py-3 px-4 rounded-lg font-semibold hover:bg-indigo-700 transition-colors flex items-center justify-center gap-2"
            >
              {copied ? '✓ Report Copied!' : '📋 Copy Full Report'}
            </button>
            <p className="text-xs text-gray-600 mt-2 text-center">
              Copy this report to include as evidence when filing a complaint
            </p>
          </div>

          <div>
            <h3 className="text-lg font-semibold text-gray-800 mb-3">Select Complaint Portal</h3>
            <div className="space-y-3">
              {complaintPortals.map((portal) => (
                <div
                  key={portal.id}
                  className="border border-gray-200 rounded-lg p-4 hover:border-indigo-400 hover:bg-indigo-50 transition-all cursor-pointer"
                  onClick={() => handleReportToPortal(portal)}
                >
                  <div className="flex items-start gap-3">
                    <span className="text-3xl">{portal.icon}</span>
                    <div className="flex-1">
                      <h4 className="font-semibold text-gray-800">{portal.name}</h4>
                      <p className="text-sm text-gray-600 mt-1">{portal.description}</p>
                      {portal.id !== 'local' && (
                        <p className="text-xs text-indigo-600 mt-2">Click to copy report & open portal →</p>
                      )}
                    </div>
                  </div>
                </div>
              ))}
            </div>
          </div>

          <div className="mt-6 p-4 bg-blue-50 border border-blue-200 rounded-lg">
            <h4 className="font-semibold text-blue-800 mb-2">📝 How to Report:</h4>
            <ol className="text-sm text-blue-700 space-y-1 list-decimal list-inside">
              <li>Click "Copy Full Report" to copy the analysis data</li>
              <li>Select a complaint portal from the list above</li>
              <li>Fill out the complaint form on the portal</li>
              <li>Paste the copied report as evidence</li>
              <li>Include any additional information requested</li>
            </ol>
          </div>
        </div>
      </div>
    </div>
  );
}

export default ReportModal;
